"""add date column

Revision ID: 9dd155222049
Revises: 4f0331d289fc
Create Date: 2021-06-22 16:32:26.737114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd155222049'
down_revision = '4f0331d289fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date')
    # ### end Alembic commands ###
