"""add comments relationship

Revision ID: f99dd2efd0b7
Revises: 92179e21dd26
Create Date: 2021-06-21 18:37:13.670150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99dd2efd0b7'
down_revision = '92179e21dd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'name')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
